"""make sync_log synced_date nullable

Revision ID: 31dd7e1db80a
Revises: 6bc3e97fd7aa
Create Date: 2026-06-09 13:46:32.822701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dd7e1db80a'
down_revision: Union[str, Sequence[str], None] = '6bc3e97fd7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_log', 'synced_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_log', 'synced_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
