"""add is_backfill to sync_log, make synced_date nullable

Revision ID: 6bc3e97fd7aa
Revises: a7c50a4f525b
Create Date: 2026-06-09 13:42:25.512754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc3e97fd7aa'
down_revision: Union[str, Sequence[str], None] = 'a7c50a4f525b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_log', sa.Column('is_backfill', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_log', 'is_backfill')
    # ### end Alembic commands ###
